server.port=8080

spring.application.name=delivery_app_aopr

spring.datasource.url=jdbc:postgresql://dpg-d8fdk0f40ujc738gvdrg-a.oregon-postgres.render.com:5432/luna_oe2j
spring.datasource.username=luna_oe2j_user
spring.datasource.password=0KmDNrBcWTIoL8TvLsGcK6s3Ue7yVLph

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true

jwt.secret=PedidosUccSecretKey2026MuySeguraParaJwtTokens1234567890
jwt.expiration-ms=86400000